# Generated by Django 5.0.6 on 2024-05-18 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releted_system_name', models.IntegerField(verbose_name='Системийн ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='SystemRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50, verbose_name='Системийн нэр')),
                ('system_type', models.PositiveIntegerField(choices=[(1, 'Карт'), (2, 'Коре'), (3, 'Дотоод'), (4, 'Дижитал')], default=1)),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Үнэлгээ')),
                ('description', models.TextField(null=True, verbose_name='Тайлбар')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хөгжүүлэгч')),
                ('related_system', models.ManyToManyField(to='root.relatedsystem', verbose_name='Холбоотой системүүд')),
            ],
        ),
    ]
