# Generated by Django 5.0.6 on 2024-05-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_relatedsystem_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemregistration',
            name='related_system',
            field=models.ManyToManyField(blank=True, to='root.relatedsystem', verbose_name='Холбоотой системүүд'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
